
version: '3'

services:
  telkkudb:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  telkkuweb:
    build: .
    container_name: telkkuweb
    ports:
      #- "443:443"
      - "65288:80"
    depends_on:
      - telkkudb

